version: "3.4"
services:
  # task_service:
  #   build: ./task_service
  #   ports:
  #     - 8000:8000
  #   expose:
  #     - "4000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin"]
      timeout: 40s
      interval: 10s
      retries: 10
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/script/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql



